apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - image: ghcr.io/paolomainardi/sigstore-demo:1.0.0
          name: sigstore-demo
          ports:
            - containerPort: 9000
              name: app
              protocol: TCP
